### ISSUE TITLE
After removing weave-npc container (part of weave-net DaemonSet) WEAVE-NPC-* iptables chains are kept

### ISSUE THREAD

**Issue by brb** [weaveworks/weave-npc#25]
Upon a termination,`weave-npc` should remove / flush chains it has created. It is probably safe to do so even in a case of `weave-npc` being restarted as it is recreates the chains during its initialization (however, the gap when a NetworkPolicy is not active would be a bit longer than it is now).

**Comment by awh** [comment]
This issue was moved to weaveworks/weave#2631
